"""Generate the Meridian Personal AI Investment Agent TRD PDF (Report route, ReportLab)."""
import hashlib
import os
import sys

PDF_SKILL_DIR = r"C:\Users\Himansu\.zcode\cli\plugins\cache\zcode-plugins-official\pdf\0.1.7\skills\pdf"
sys.path.insert(0, os.path.join(PDF_SKILL_DIR, "scripts"))

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import cm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.pdfmetrics import registerFontFamily
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import (CondPageBreak, HRFlowable, KeepTogether, PageBreak,
                                Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle)
from reportlab.platypus.tableofcontents import TableOfContents

HERE = os.path.dirname(os.path.abspath(__file__))
OUT_DIR = os.path.dirname(HERE)
BODY_PDF = os.path.join(HERE, "trd_body.pdf")

# ━━ Fonts (Windows host) ━━
FONTS = r"C:\Windows\Fonts"
pdfmetrics.registerFont(TTFont("Times New Roman", os.path.join(FONTS, "times.ttf")))
pdfmetrics.registerFont(TTFont("Times New Roman-Bold", os.path.join(FONTS, "timesbd.ttf")))
pdfmetrics.registerFont(TTFont("Times New Roman-Italic", os.path.join(FONTS, "timesi.ttf")))
pdfmetrics.registerFont(TTFont("Consolas", os.path.join(FONTS, "consola.ttf")))
registerFontFamily("Times New Roman", normal="Times New Roman", bold="Times New Roman-Bold",
                   italic="Times New Roman-Italic", boldItalic="Times New Roman-Bold")
registerFontFamily("Consolas", normal="Consolas", bold="Consolas")

# ━━ Cascade Palette (auto-generated by design_engine.py palette-cascade) ━━
HEADER_FILL = colors.HexColor("#334a55")
TABLE_STRIPE = colors.HexColor("#eaeced")
CARD_BG = colors.HexColor("#eceeef")
BORDER = colors.HexColor("#c9d2d6")
ICON = colors.HexColor("#476b7e")
ACCENT = colors.HexColor("#a5263b")
TEXT_PRIMARY = colors.HexColor("#232627")
TEXT_MUTED = colors.HexColor("#737a7d")
SEM_SUCCESS = colors.HexColor("#497d5a")
SEM_WARNING = colors.HexColor("#ac8a47")

PAGE_W, PAGE_H = A4
MARGIN = 2.0 * cm
CONTENT_W = PAGE_W - 2 * MARGIN

# ━━ Styles ━━
body = ParagraphStyle("Body", fontName="Times New Roman", fontSize=10.5, leading=15.5,
                      alignment=TA_JUSTIFY, textColor=TEXT_PRIMARY, spaceAfter=8)
lead = ParagraphStyle("Lead", parent=body, fontSize=11, leading=16.5, textColor=TEXT_PRIMARY)
bullet = ParagraphStyle("Bullet", parent=body, leftIndent=14, bulletIndent=2, spaceAfter=4)
h1 = ParagraphStyle("H1", fontName="Times New Roman", fontSize=19, leading=24,
                    textColor=TEXT_PRIMARY, spaceBefore=0, spaceAfter=4)
h2 = ParagraphStyle("H2", fontName="Times New Roman", fontSize=13.5, leading=17,
                    textColor=ICON, spaceBefore=14, spaceAfter=6)
h3 = ParagraphStyle("H3", fontName="Times New Roman", fontSize=11.5, leading=15,
                    textColor=TEXT_PRIMARY, spaceBefore=10, spaceAfter=4)
caption = ParagraphStyle("Caption", fontName="Times New Roman", fontSize=8.5, leading=11,
                         alignment=TA_CENTER, textColor=TEXT_MUTED, spaceBefore=3, spaceAfter=6)
th = ParagraphStyle("TH", fontName="Times New Roman", fontSize=9.5, leading=12,
                    textColor=colors.white, alignment=TA_LEFT)
td = ParagraphStyle("TD", fontName="Times New Roman", fontSize=9.5, leading=12.5,
                    textColor=TEXT_PRIMARY, alignment=TA_LEFT)
code_st = ParagraphStyle("Code", fontName="Consolas", fontSize=8, leading=11,
                         textColor=TEXT_PRIMARY)
quote_st = ParagraphStyle("Quote", parent=body, fontName="Times New Roman-Italic",
                          leftIndent=24, leading=14, textColor=TEXT_PRIMARY, spaceBefore=4)
bullet_tight = ParagraphStyle("BulletTight", parent=bullet, spaceAfter=2)
stat_big = ParagraphStyle("StatBig", fontName="Times New Roman", fontSize=16, leading=19,
                          textColor=ACCENT, alignment=TA_CENTER)
stat_lbl = ParagraphStyle("StatLbl", fontName="Times New Roman", fontSize=8, leading=10.5,
                          textColor=TEXT_MUTED, alignment=TA_CENTER)

H1_ORPHAN = (PAGE_H - 4.2 * cm) * 0.15


def heading(text, style, level):
    key = "h_" + hashlib.md5(text.encode()).hexdigest()[:8]
    p = Paragraph('<a name="%s"/><b>%s</b>' % (key, text), style)
    p.bookmark_name = text
    p.bookmark_level = level
    p.bookmark_text = text
    p.bookmark_key = key
    return p


def section(story, num_title):
    story.append(CondPageBreak(H1_ORPHAN))
    story.append(Spacer(1, 14))
    story.append(heading(num_title, h1, 0))
    story.append(HRFlowable(width="100%", thickness=1.2, color=ACCENT, spaceBefore=2, spaceAfter=10))


def sub(story, text):
    story.append(CondPageBreak(60))
    story.append(heading(text, h2, 1))


def para(story, text, style=body):
    story.append(Paragraph(text, style))


def bullets(story, items, style=bullet):
    for it in items:
        story.append(Paragraph("• " + it, style))
    story.append(Spacer(1, 4))


def table(story, headers, rows, ratios, cap=None, keep_with_cap=True):
    data = [[Paragraph("<b>%s</b>" % h, th) for h in headers]]
    for r in rows:
        data.append([Paragraph(c, td) for c in r])
    t = Table(data, colWidths=[x * CONTENT_W for x in ratios], hAlign="CENTER", repeatRows=1)
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), HEADER_FILL),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, TABLE_STRIPE]),
        ("GRID", (0, 0), (-1, -1), 0.5, BORDER),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))
    story.append(Spacer(1, 8))
    if cap and keep_with_cap and len(rows) <= 12:
        story.append(KeepTogether([t, Paragraph(cap, caption)]))
    else:
        story.append(t)
        if cap:
            story.append(Paragraph(cap, caption))
    story.append(Spacer(1, 8))


def code_block(story, text, cap=None):
    para_text = "<br/>".join(text.replace(" ", " ").split("\n"))
    inner = Paragraph(para_text, code_st)
    t = Table([[inner]], colWidths=[CONTENT_W * 0.96], hAlign="CENTER")
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), CARD_BG),
        ("BOX", (0, 0), (-1, -1), 0.75, BORDER),
        ("LEFTPADDING", (0, 0), (-1, -1), 10),
        ("RIGHTPADDING", (0, 0), (-1, -1), 10),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
    ]))
    story.append(Spacer(1, 6))
    story.append(t)
    if cap:
        story.append(Paragraph(cap, caption))
    story.append(Spacer(1, 6))


def stat_row(story, stats):
    cells, labels = [], []
    for value, label in stats:
        cells.append(Paragraph("<b>%s</b>" % value, stat_big))
        labels.append(Paragraph(label, stat_lbl))
    t = Table([cells, labels], colWidths=[CONTENT_W / len(stats)] * len(stats), hAlign="CENTER")
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), CARD_BG),
        ("BOX", (0, 0), (-1, -1), 1, ACCENT),
        ("LINEBEFORE", (1, 0), (-1, -1), 0.5, BORDER),
        ("TOPPADDING", (0, 0), (-1, 0), 10),
        ("BOTTOMPADDING", (0, -1), (-1, -1), 10),
        ("TOPPADDING", (0, -1), (-1, -1), 2),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    story.append(Spacer(1, 8))
    story.append(KeepTogether(t))
    story.append(Spacer(1, 8))


# ━━ Document template with TOC + header/footer ━━
class TocDocTemplate(SimpleDocTemplate):
    def afterFlowable(self, flowable):
        if hasattr(flowable, "bookmark_name"):
            self.notify("TOCEntry", (flowable.bookmark_level, flowable.bookmark_text,
                                     self.page, flowable.bookmark_key))


def header_footer(canvas, doc):
    canvas.saveState()
    canvas.setFont("Times New Roman", 7.5)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(MARGIN, PAGE_H - 1.2 * cm, "Meridian - Personal AI Investment Agent  |  Technical Requirements Document v1.0")
    canvas.setStrokeColor(ACCENT)
    canvas.setLineWidth(1.2)
    canvas.line(MARGIN, PAGE_H - 1.38 * cm, PAGE_W - MARGIN, PAGE_H - 1.38 * cm)
    canvas.setStrokeColor(BORDER)
    canvas.setLineWidth(0.5)
    canvas.line(MARGIN, 1.35 * cm, PAGE_W - MARGIN, 1.35 * cm)
    canvas.drawString(MARGIN, 1.0 * cm, "Meridian Market Desk")
    canvas.drawRightString(PAGE_W - MARGIN, 1.0 * cm, "Page %d" % doc.page)
    canvas.restoreState()


doc = TocDocTemplate(BODY_PDF, pagesize=A4,
                     leftMargin=MARGIN, rightMargin=MARGIN,
                     topMargin=2.2 * cm, bottomMargin=1.9 * cm,
                     title="Meridian - Personal AI Investment Agent: Technical Requirements Document",
                     author="Z.ai", creator="Z.ai",
                     subject="TRD: production-grade architecture for the Meridian personal market intelligence platform")

story = []

# ━━ TOC page ━━
toc = TableOfContents()
toc.levelStyles = [
    ParagraphStyle("TOC1", fontName="Times New Roman", fontSize=11.5, leading=16, leftIndent=16,
                   firstLineIndent=-16, spaceBefore=3, textColor=TEXT_PRIMARY),
    ParagraphStyle("TOC2", fontName="Times New Roman", fontSize=10, leading=13.5, leftIndent=34,
                   firstLineIndent=-16, spaceBefore=1, textColor=TEXT_MUTED),
]
story.append(Spacer(1, 10))
story.append(Paragraph("<b>Table of Contents</b>", ParagraphStyle(
    "TocTitle", parent=h1, fontSize=17, spaceAfter=8)))
story.append(HRFlowable(width="100%", thickness=1.2, color=ACCENT, spaceBefore=0, spaceAfter=12))
story.append(toc)
story.append(PageBreak())

# ════════ 1. Document Control ════════
section(story, "1. Document Control")
table(story, ["Field", "Value"], [
    ["Product", "Meridian - Personal AI Investment Agent (PA)"],
    ["Document type", "Technical Requirements Document (TRD)"],
    ["Source document", "Personal AI Investment Agent PRD v1.0 (September 2026)"],
    ["Audience", "Founder / developer / designer"],
    ["Current frontend", "Next.js 16 + React 19 + TypeScript (strict) + Tailwind CSS 4 + Recharts"],
    ["Planned backend", "Java 21 + Spring Boot 3.5.x, PostgreSQL 16, Redis 7, Spring AI 1.x"],
    ["Financial safety posture", "Decision support first; no autonomous order placement in MVP"],
    ["Status", "Frontend foundation delivered; backend build starts after this document"],
], [0.24, 0.76], cap="Table 1-1: Document control")
para(story,
     "This TRD translates the approved PRD into an implementable technical blueprint. It fixes the "
     "system architecture, the backend technology decisions (Spring Boot), the market-data provider "
     "strategy derived from primary research, the alert-rule engine and AI-agent designs, the data "
     "model, the API contract, and the phased delivery plan. The frontend is being built first; the "
     "backend contract defined here is what the frontend is coded against from day one.")

# ════════ 2. System Overview ════════
section(story, "2. System Overview and Architecture")
sub(story, "2.1 Product context")
para(story,
     "Meridian is a personal market intelligence system that behaves like an always-on financial "
     "research assistant. It combines near-real-time market data, portfolio context, user preferences, "
     "configurable monitoring rules, news and IPO information, deterministic calculations, and an "
     "LLM-based agent interface. Its defining feature is persistent personalization: the system knows "
     "what the user owns, watches, and which thresholds matter. It supports reactive conversations "
     "(\"analyze Tata Steel\") and proactive behavior (\"tell me when Tata Steel reaches the 200-day average\").",
     lead)
sub(story, "2.2 Architecture at a glance")
table(story, ["Component", "Technology", "Responsibility"], [
    ["Web frontend", "Next.js 16 (App Router), React 19, Tailwind 4",
     "All user-facing screens; module-driven structure; talks to backend REST API only"],
    ["Backend API", "Spring Boot 3.5 (Java 21), REST, springdoc-openapi",
     "Authentication, profile, portfolio, watchlist, alerts CRUD, market proxies, agent chat"],
    ["Rule engine", "Spring scheduling + ShedLock, in-memory condition-tree evaluator",
     "Evaluates active AlertRules against cached market snapshots on a fixed cadence"],
    ["AI agent", "Spring AI 1.x (ChatClient, tool calling), OpenAI-compatible LLM API",
     "Natural-language understanding, explanation, portfolio/stock interpretation; never the source of truth"],
    ["Data layer", "PostgreSQL 16 (JPA + Flyway), Redis 7 (Spring Data Redis)",
     "System of record; quote/news/IPO caching, rate-limit counters, scheduler locks"],
    ["Integrations", "Provider adapters (Yahoo/Dhan/EODHD, Google News RSS/Marketaux, Apify IPO)",
     "External market data, news and IPO feeds behind internal provider interfaces"],
    ["Notifications", "In-app + email (SMTP) first; web push, Telegram later",
     "Delivers triggered alerts and digests; full delivery history retained"],
], [0.16, 0.30, 0.54], cap="Table 2-1: Core components and responsibilities")
sub(story, "2.3 Architecture principles")
bullets(story, [
    "<b>Tool-first AI.</b> The LLM orchestrates; deterministic services compute. The agent calls backend tools for every current number and never invents data.",
    "<b>Deterministic core.</b> Portfolio metrics, rule evaluation and scanner logic are plain code, unit-testable and auditable; the AI only interprets results.",
    "<b>Provider abstraction.</b> Every external feed sits behind an internal interface (MarketDataProvider, NewsProvider, IpoProvider, NotificationChannel) so vendors are replaceable without schema changes.",
    "<b>Asset-level batching.</b> One quote fetch per symbol per cycle feeds all users' rules; never one external request per user rule.",
    "<b>User-scoped isolation.</b> Every row that carries user data is keyed by user_id and authorized at the service layer.",
    "<b>Decision-support posture.</b> No order placement in MVP; estimates are labelled; data freshness (timestamp + source) is always displayed.",
])

# ════════ 3. Technology Stack ════════
section(story, "3. Technology Stack and Key Decisions")
table(story, ["Layer", "Technology", "Version", "Rationale"], [
    ["Frontend", "Next.js (App Router), React, TypeScript strict", "16 / 19",
     "Already delivered; module-driven src/ structure; SSR + static hybrid fits dashboard content"],
    ["Frontend UI", "Tailwind CSS, Recharts, lucide-react", "4 / 3.x",
     "Utility styling with design tokens; charts for price history and allocation"],
    ["Backend runtime", "Java (virtual threads enabled)", "21 LTS",
     "Mature ecosystem; virtual threads make blocking I/O to providers simple and scalable"],
    ["Backend framework", "Spring Boot (Web, Security, Validation, Actuator)", "3.5.x",
     "Industry-standard REST stack; first-class Spring AI and Spring Data integration"],
    ["Persistence", "PostgreSQL + Spring Data JPA + Flyway", "16",
     "Relational fits the entity model; JSONB for condition trees; migrations are code-reviewed"],
    ["Cache / counters", "Redis + Spring Data Redis", "7",
     "Quote cache, provider rate-limit tokens, idempotency keys, scheduler locks (ShedLock)"],
    ["AI", "Spring AI (ChatClient, @Tool, structured output)", "1.x",
     "Declarative tool calling and typed entity conversion; provider-agnostic LLM client"],
    ["Resilience", "Resilience4j (retry, rate limiter, circuit breaker, fallback)", "2.x",
     "Provider latency/limits are the main failure source; fallback must degrade gracefully"],
    ["Docs / API", "springdoc-openapi (Swagger UI)", "2.x",
     "The API contract in this TRD is published as OpenAPI and kept executable"],
    ["Build / run", "Maven, Docker Compose, GitHub Actions", "-",
     "One compose file boots postgres, redis, api, web for local and staging"],
], [0.15, 0.33, 0.10, 0.42], cap="Table 3-1: Technology decisions")
para(story,
     "Deliberate non-choices: no Kafka/RabbitMQ (scheduled polling plus transactional outbox covers "
     "MVP scale), no microservices (one modular monolith with strict package boundaries), no ORM "
     "magic beyond JPA (hot paths use explicit queries), and no client-side market data (all provider "
     "calls are server-side to protect keys and control rate limits).")

# ════════ 4. Market Data Research ════════
section(story, "4. Market Data Research and Provider Strategy")
para(story,
     "Primary research (September 2026) into Indian-market data sources drives the provider strategy. "
     "The headline finding: <b>global freemium APIs serve NSE/BSE data only delayed or end-of-day</b>; "
     "true real-time feeds come from broker APIs (free to cheap for personal use) or licensed vendors.")
sub(story, "4.1 Provider landscape")
table(story, ["Provider", "Coverage", "Latency", "Cost", "Assessment"], [
    ["Yahoo Finance chart API (unofficial)", "NSE/BSE quotes + 1-10y daily history", "~15 min delayed", "Free",
     "Current default. No key, generous limits, but ToS grey area and no SLA; must cache aggressively and label freshness"],
    ["Alpha Vantage", "NSE EOD + fundamentals", "EOD", "Free 25 req/day",
     "Useful fundamentals fallback; rate limit too low for quotes"],
    ["Twelve Data", "NSE quotes + history, WebSocket", "Delayed / EOD", "Freemium",
     "Clean API; India real-time not guaranteed; viable paid alternative"],
    ["EODHD", "NSE/BSE EOD + fundamentals + splits", "EOD", "From ~USD 20/mo",
     "Best structured EOD + fundamentals for Phase 2 research features"],
    ["Finnhub", "Primarily US", "-", "Freemium", "Skipped: weak India coverage"],
    ["NSE official site", "Full NSE", "Real-time", "Free (scraping)",
     "No public API; scraping is ToS-restricted and brittle; excluded"],
    ["DhanHQ (broker API)", "NSE/BSE REST + WebSocket + historical ticks", "Real-time", "Free for personal use",
     "Best Phase 2 real-time feed: free market feed, no subscription for API access"],
    ["Angel One SmartAPI", "NSE/BSE REST + WebSocket", "Real-time", "Free with account",
     "Strong free alternative; used as second broker adapter"],
    ["Upstox API", "NSE/BSE REST + WebSocket", "Real-time", "~INR 150+/yr from year 2",
     "Cheap alternative; keep behind the same adapter"],
    ["Zerodha Kite Connect", "Full trading + feed + historical", "Real-time", "~INR 500-2,000/mo per app",
     "Most mature; relevant at V4 when broker sync / trading lands"],
    ["TrueData / GlobalDataFeeds", "Licensed real-time NSE/BSE", "Real-time", "Commercial",
     "Only if the product scales beyond personal use"],
], [0.185, 0.235, 0.10, 0.115, 0.365], cap="Table 4-1: Indian market data providers (researched September 2026)")
sub(story, "4.2 News and IPO data")
table(story, ["Source", "Use", "Notes"], [
    ["Google News RSS", "News provider now (frontend MVP already uses it)",
     "Free, no key; company/topic queries with when:7d filter; relevance scoring happens in-app"],
    ["Marketaux", "News provider Phase 2", "Entity/ticker tagging across 80+ markets including NSE; free monthly quota; best fit for per-company relevance"],
    ["GNews / NewsAPI.org", "Fallback search providers", "100 req/day free tiers; NewsAPI free tier is dev-only with 24h delay; GNews supports country=in"],
    ["Apify India IPO Tracker", "IPO provider Phase 2", "Clean JSON of upcoming IPOs, GMP and live QIB/NII/Retail subscription from BSE/NSE"],
    ["Chittorgarh / InvestorGain", "IPO subscription fallback", "The de-facto sources for live subscription status; no official API, so access via the Apify actor or a maintained parser with caching"],
], [0.185, 0.235, 0.58], cap="Table 4-2: News and IPO sources")
sub(story, "4.3 Recommended strategy")
bullets(story, [
    "<b>Phase 1 (MVP):</b> MarketDataProvider backed by the Yahoo chart adapter with 60-second Redis caching per symbol, source + timestamp stored on every snapshot, and Resilience4j fallback to last-known-good quotes labelled STALE.",
    "<b>Phase 2 (real-time + fundamentals):</b> add a DhanHQ WebSocket adapter for live quotes of watchlist symbols (free, licensed feed via broker account), and EODHD for EOD history and fundamentals.",
    "<b>Phase 3 (V4, broker sync):</b> Kite Connect or SmartAPI adapters for read-only holdings sync; order workflows only with explicit confirmation, after legal review.",
    "<b>News:</b> Google News RSS now; Marketaux adapter behind the same NewsProvider interface when entity tagging is needed for the relevance engine.",
    "<b>IPO:</b> Apify India IPO Tracker actor behind IpoProvider; every allotment estimate is labelled with its methodology, and subscription figures carry their source and fetch time.",
])
para(story,
     "All provider interfaces return a normalized internal model (the QuoteSnapshot / NewsArticle / "
     "IPO entities of section 8) and attach provider name + provider timestamp. Missing values are "
     "never fabricated: the UI renders \"data unavailable\" with the last-good timestamp.")

# ════════ 5. Backend Architecture ════════
section(story, "5. Backend Architecture (Spring Boot)")
sub(story, "5.1 Module structure")
para(story, "A modular monolith: one deployable with package boundaries enforced by ArchUnit tests. "
            "Domains mirror the frontend modules, which keeps the codebase mentally symmetric.")
code_block(story,
"""meridian-api/
+-- api/                 # REST controllers, request/response DTOs, error handling
|   +-- auth, profile, portfolio, watchlist, alerts, market, agent, news, ipo
+-- core/
|   +-- auth/            # users, credentials, JWT issuance, refresh tokens
|   +-- portfolio/       # holdings, transactions, metrics calculator
|   +-- watchlist/       # watchlist items, symbol master
|   +-- market/          # MarketDataProvider port, quote snapshots, indicators
|   +-- alerts/          # AlertRule, conditionTree model, evaluator, cooldown, history
|   +-- notify/          # NotificationChannel port, in-app + email adapters, digests
|   +-- agent/           # Spring AI ChatClient, @Tool registry, conversations, audit
|   +-- research/        # stock analysis layers, portfolio analysis orchestration
|   +-- ipo/             # IpoProvider port, IPO master, subscription snapshots
|   +-- news/            # NewsProvider port, articles cache, relevance scoring
+-- integrations/        # yahoo, dhan, eodhd, googlenews, marketaux, apify, smtp
+-- config/              # security, redis, scheduling, spring-ai, resilience, openapi
+-- db/migration/        # Flyway V1__init.sql, V2__...
""",
     cap="Listing 5-1: Backend package layout")
sub(story, "5.2 Cross-cutting components")
table(story, ["Concern", "Mechanism", "Notes"], [
    ["Authentication", "Spring Security 6, JWT access (15 min) + refresh (30 d) tokens",
     "Stateless; BCrypt password hashing; all app endpoints authenticated except /api/v1/auth/**"],
    ["Authorization", "Service-level user checks (owner-or-404)",
     "Every repository query filters by principal user id; integration tests prove isolation"],
    ["Caching", "Redis: quotes 60 s, news 5 min, IPO 10 min; TTL per provider",
     "Cache key = provider + symbol + interval; stale-while-error returns last good value flagged STALE"],
    ["Scheduling", "Spring @Scheduled + ShedLock (JDBC/Redis lock provider)",
     "Safe single-node or multi-node; cadences per section 6.3"],
    ["Resilience", "Resilience4j per integration: retry (2x, jitter), rate limiter, circuit breaker, fallback",
     "Provider outages degrade to cached/stale data, never to fabricated numbers"],
    ["AI integration", "Spring AI ChatClient + @Tool registry; OpenAI-compatible endpoint",
     "Model and base URL are configuration; token usage recorded per request for cost metrics"],
    ["Observability", "Actuator + Micrometer + structured JSON logs; provider health indicators",
     "Metrics: provider latency/error/limit, scheduler lag, AI tokens/cost, cache hit ratio"],
    ["API docs", "springdoc-openapi UI at /swagger-ui", "Contract-first checking against section 9"],
], [0.16, 0.40, 0.44], cap="Table 5-1: Cross-cutting components")

# ════════ 6. Alert Rule Engine ════════
section(story, "6. Alert Rule Engine Design")
sub(story, "6.1 Rule model")
para(story,
     "The differentiator is a generic rule model instead of a fixed alert catalog. Every rule carries a "
     "JSONB conditionTree so nested AND/OR conditions of any family (price, percentage, volume, portfolio "
     "weight, fundamental, news, periodic) are representable without schema migrations.")
code_block(story,
"""AlertRule {
  id, userId, assetType, symbol,
  conditionTree: {                       // JSONB
    type: "AND",
    children: [
      { type: "PRICE",  symbol: "TATASTEEL.NS", operator: ">=", value: 200 },
      { type: "NEWS",   symbol: "TATASTEEL.NS", eventType: "RESULTS", sentiment: "NEGATIVE" }
    ]
  },
  triggerMode: ONE_TIME | RECURRING | PERSISTENT,
  cooldownMinutes, notificationChannels[], active,
  createdBy: USER | AGENT, lastTriggeredAt, createdAt
}""",
     cap="Listing 6-1: Alert rule model")
sub(story, "6.2 Evaluation pipeline")
bullets(story, [
    "Scheduler tick: load distinct symbols referenced by active rules (asset-level batching).",
    "Fetch quotes cache-first (Redis 60 s TTL; miss goes to the provider through Resilience4j).",
    "Evaluate every matching rule's conditionTree in memory against the snapshot - a pure function, unit-tested per rule family.",
    "For true rules: apply cooldown (rule.lastTriggeredAt + cooldownMinutes) and duplicate suppression (unique rule_id + cycle key).",
    "Persist the trigger to alert history, create a Notification row per configured channel, and hand off to the delivery dispatcher.",
    "ONE_TIME rules deactivate after firing; RECURRING rules re-arm on their schedule; PERSISTENT rules stay armed until disabled.",
])
sub(story, "6.3 Background job cadences")
table(story, ["Job", "Cadence", "Purpose"], [
    ["Price rule monitor", "Every 60 s within market hours; 5 min off-hours",
     "Evaluate price / percentage / volume triggers"],
    ["News monitor", "Every 10 min", "Detect new relevant company / sector / market events"],
    ["Portfolio monitor", "Hourly (user-configurable)", "Concentration, allocation limits, major movements"],
    ["IPO monitor", "Every 30 min during bidding windows", "Opening/closing, subscription milestones, listing"],
    ["Daily summary", "Once daily after close", "Personalized end-of-day report (deterministic template first, AI summary in V2)"],
    ["Weekly review", "Weekly", "Portfolio, thesis changes, watchlist events"],
], [0.22, 0.30, 0.48], cap="Table 6-1: Scheduled jobs (PRD section 10)")
stat_row(story, [
    ("60 s", "Quote freshness inside market hours"),
    ("1", "Notification per cooldown window"),
    ("0", "Per-user-rule provider calls"),
])

# ════════ 7. AI Agent ════════
section(story, "7. AI Agent Architecture (Spring AI)")
sub(story, "7.1 Orchestration flow")
para(story,
     "The agent is an orchestration layer, not the source of truth. A user message reaches the agent "
     "service, which selects and executes backend tools, receives structured results, and produces an "
     "explanation or a proposed action. Material actions (rule changes) are executed by deterministic "
     "services and are audited either way.")
code_block(story,
"""User message
 -> Agent service (Spring AI ChatClient + conversation memory)
 -> Tool selection (@Tool methods, JSON-schema described)
 -> Tool execution against core services (market / portfolio / alerts / ipo / news)
 -> Structured tool result
 -> LLM interpretation (facts | calculations | interpretation | assumptions)
 -> Response, or proposed action requiring user confirmation""",
     cap="Listing 7-1: Agent request flow")
sub(story, "7.2 Tool registry (initial set)")
table(story, ["Tool", "Backed by", "Returns"], [
    ["get_stock_quote(symbol)", "market/QuoteService", "QuoteSnapshot + indicators"],
    ["get_stock_history(symbol, range)", "market/HistoryService", "OHLCV series"],
    ["get_company_fundamentals(symbol)", "research/FundamentalsService", "PE, margins, ROE, debt (provider-dependent)"],
    ["get_latest_news(symbol or topic)", "news/NewsService", "Relevance-scored articles"],
    ["get_portfolio / get_portfolio_metrics / get_holding", "portfolio/PortfolioService", "Positions, value, P&L, allocation, concentration"],
    ["get_watchlist", "watchlist/WatchlistService", "Watchlist items"],
    ["create_alert / update_alert / delete_alert / get_active_alerts", "alerts/AlertService", "AlertRule mutations + list (audited, createdBy=AGENT)"],
    ["get_upcoming_ipos / get_ipo_details / get_ipo_subscription", "ipo/IpoService", "IPO master + subscription snapshots"],
    ["analyze_stock(symbol) / analyze_portfolio()", "research/AnalysisService", "Layered evidence summary (fundamentals, valuation, technicals, news, portfolio fit)"],
], [0.34, 0.27, 0.39], cap="Table 7-1: Agent tools")
sub(story, "7.3 Guardrails and audit")
bullets(story, [
    "System prompt (Appendix A) enforces: use tools for current data; never invent data; separate facts, calculations, interpretations and assumptions; no guaranteed-return claims; say when data is stale.",
    "Structured intents: free-text like \"Tata Steel 200 par aaye tyare alert karje\" is converted with .entity(CreateAlertIntent.class) into a typed payload, validated server-side, then persisted by the normal AlertService.",
    "Every tool execution writes an AgentAction row (tool, input, result digest, conversation, confirmation status) - AC-12 auditability.",
    "Token usage and latency are recorded per request for cost monitoring; a per-user daily token budget guards runaway cost.",
    "Agent-created rules are visible and editable in the Alerts UI (UI remains the source of truth for configuration).",
])

# ════════ 8. Data Model ════════
section(story, "8. Data Model and Persistence")
table(story, ["Entity", "Key fields", "Notes"], [
    ["users", "id, email, password_hash, name, timezone, currency", "Account identity; auth via Spring Security"],
    ["user_preferences", "user_id, risk_level, horizon, budget, allocation_limits jsonb, sector_prefs", "Personalization inputs for the agent"],
    ["holdings", "user_id, symbol, quantity, avg_buy_price, thesis", "Current portfolio; transactions table lands in V4"],
    ["watchlist_items", "user_id, symbol, type", "Owned or unowned monitoring"],
    ["alert_rules", "user_id, asset_type, symbol, condition_tree jsonb, trigger_mode, cooldown_minutes, channels[], active, created_by, last_triggered_at", "Section 6 model"],
    ["alert_events", "rule_id, triggered_at, snapshot jsonb", "Trigger history; powers the alerts timeline"],
    ["notifications", "user_id, event_id, rule_id, title, body, severity, channel, status, sent_at", "Full delivery history"],
    ["instruments", "symbol, exchange, name, sector", "Symbol master seeded per user universe"],
    ["quote_snapshots", "symbol, price, volume, provider, provider_time, fetched_at", "Market observations (also the stale-fallback source)"],
    ["news_articles", "provider_id, symbol_or_topic, published_at, relevance", "News cache with dedupe on provider_id"],
    ["ipos", "company, open/close dates, price band, lot_size, issue_size", "IPO master"],
    ["ipo_subscription_snapshots", "ipo_id, timestamp, qib/nii/retail", "Subscription history"],
    ["conversations / messages", "user_id, title / conversation_id, role, content, tool_meta jsonb", "Agent memory and history"],
    ["investment_theses", "user_id, symbol, thesis, assumptions, review_at", "Long-term memory (V3)"],
    ["agent_actions", "conversation_id, tool, input jsonb, result_digest, confirmed, status", "Auditability (AC-12)"],
], [0.20, 0.44, 0.36], cap="Table 8-1: Entity model (PostgreSQL, Flyway-managed)")
bullets(story, [
    "condition_tree and allocation_limits are JSONB - new rule families need no migration.",
    "Every user-scoped table carries user_id with composite indexes (user_id, symbol) for the hot paths.",
    "Flyway migrations are the only schema path; V1 creates auth + portfolio + alerts MVP tables.",
])

# ════════ 9. API Contract ════════
section(story, "9. API Contract")
sub(story, "9.1 Conventions")
bullets(story, [
    "Base path /api/v1; JSON bodies; camelCase fields; ISO-8601 timestamps with offset.",
    "Auth: Authorization: Bearer <JWT> on every endpoint except /api/v1/auth/**.",
    "Errors: RFC 7807 application/problem+json with type, title, status, detail, traceId.",
    "Lists are cursor-paginated (?cursor=, ?limit=, max 100); market queries accept symbol lists capped at 28.",
    "All endpoints are user-scoped server-side; ids are UUIDs.",
])
sub(story, "9.2 Endpoint inventory")
table(story, ["Method", "Endpoint", "Purpose", "Auth"], [
    ["POST", "/api/v1/auth/register", "Create account", "Public"],
    ["POST", "/api/v1/auth/login", "Authenticate, issue tokens", "Public"],
    ["POST", "/api/v1/auth/refresh", "Rotate access token", "Refresh token"],
    ["GET", "/api/v1/profile", "Get user profile", "Bearer"],
    ["PUT", "/api/v1/profile/preferences", "Update preferences (risk, horizon, limits)", "Bearer"],
    ["GET", "/api/v1/portfolio", "Portfolio with computed metrics", "Bearer"],
    ["POST / PUT / DELETE", "/api/v1/portfolio/holdings[/{id}]", "Manage holdings", "Bearer"],
    ["GET / POST", "/api/v1/watchlist", "List / add watch items", "Bearer"],
    ["DELETE", "/api/v1/watchlist/{symbol}", "Remove watch item", "Bearer"],
    ["GET / POST", "/api/v1/alerts", "List rules / create rule", "Bearer"],
    ["PUT / DELETE", "/api/v1/alerts/{id}", "Edit / delete rule", "Bearer"],
    ["GET", "/api/v1/alerts/events", "Trigger history", "Bearer"],
    ["GET", "/api/v1/notifications", "Notification list + unread count", "Bearer"],
    ["POST", "/api/v1/agent/chat", "Chat with PA (streams SSE)", "Bearer"],
    ["GET", "/api/v1/agent/conversations/{id}", "Conversation history", "Bearer"],
    ["GET", "/api/v1/stocks/{symbol}", "Quote + indicators + freshness", "Bearer"],
    ["GET", "/api/v1/stocks/{symbol}/analysis", "Layered stock analysis", "Bearer"],
    ["GET / POST / DELETE", "/api/v1/news[?symbol=]", "Relevance-filtered news", "Bearer"],
    ["GET", "/api/v1/ipos, /api/v1/ipos/{id}, /{id}/subscription", "IPO list, details, subscription", "Bearer"],
], [0.14, 0.34, 0.38, 0.14], cap="Table 9-1: API surface (v1)")
sub(story, "9.3 Example payloads")
code_block(story,
"""POST /api/v1/alerts
{ "assetType": "EQUITY", "symbol": "TATASTEEL.NS",
  "conditionTree": { "type": "PRICE", "operator": ">=", "value": 200 },
  "triggerMode": "ONE_TIME", "cooldownMinutes": 0,
  "notificationChannels": ["IN_APP", "EMAIL"] }

201 Created
{ "id": "9f1c...", "symbol": "TATASTEEL.NS", "active": true,
  "createdBy": "USER", "createdAt": "2026-09-26T10:12:00+05:30" }

409 Conflict (problem+json)
{ "type": "https://meridian.app/problems/symbol-unknown",
  "title": "Unknown symbol", "status": 409,
  "detail": "TATASTEEL.BOGO does not match any instrument", "traceId": "..." }""",
     cap="Listing 9-1: Create-alert contract")

# ════════ 10. Security ════════
section(story, "10. Security and Compliance")
table(story, ["Area", "Measure"], [
    ["Authentication", "Spring Security 6 + JWT; BCrypt (strength 12); refresh-token rotation with reuse detection"],
    ["Session / token handling", "Short-lived access tokens; refresh tokens stored hashed; revocation list in Redis"],
    ["Transport", "HTTPS everywhere (HSTS); no provider keys in the browser, ever"],
    ["Data isolation", "User-scoped queries enforced in repositories; authorization tests per endpoint (AC-14)"],
    ["At rest", "PostgreSQL volume encryption at the platform layer; sensitive columns (token hashes) hashed"],
    ["Audit", "AgentAction + alert_events + notification delivery records; append-only"],
    ["Secrets", "Environment/secret-store only (no secrets in git); .env excluded by .gitignore; rotation runbook"],
    ["AI safety", "Tool allow-list, output schema validation, no LLM write access beyond the alert rule services"],
    ["Financial safety", "Decision-support positioning; explicit uncertainty on estimates; no order placement in MVP"],
    ["Provider licensing", "Respect provider ToS; per-provider attribution and freshness labels in the UI"],
], [0.22, 0.78], cap="Table 10-1: Security controls")

# ════════ 11. Frontend Architecture ════════
section(story, "11. Frontend Architecture")
sub(story, "11.1 Current module map (delivered)")
para(story,
     "The codebase was restructured into a module-driven src/ layout. Each feature module owns its "
     "components, hooks and logic and exposes a public index.ts; shared UI primitives and formatting "
     "live in components/ and lib/; domain types are split per area in types/. API route handlers "
     "(proxying Yahoo/Google News) keep the current local mode working without a backend.")
table(story, ["Module", "Owns", "Screen"], [
    ["modules/market", "MarketProvider store, InstrumentPanel, NewsList, PriceChart, TradingViewWidget, yahoo/news adapters, indicators, seed", "(core)"],
    ["modules/dashboard", "CommandView - portfolio health, alerts, news, scanner digest", "/ (dashboard)"],
    ["modules/markets", "MarketsView - watchlist grid", "/markets"],
    ["modules/portfolio", "PortfolioView, calculatePortfolio", "/portfolio"],
    ["modules/alerts", "AlertsView, AlertList, alert logic", "/alerts"],
    ["modules/scanner", "ScannerView, useScanner, scanner engine", "/scanner"],
    ["modules/research", "ResearchView", "/research"],
    ["components / lib / types", "Shell, ui primitives, format utils, per-domain types", "(shared)"],
], [0.20, 0.55, 0.25], cap="Table 11-1: Frontend modules today")
sub(story, "11.2 Backend integration strategy (this release)")
para(story,
     "A typed API-client layer is being added now so the Spring Boot backend can be plugged in later "
     "without touching screens. An environment switch selects the data source; both adapters implement "
     "the same TypeScript contracts.")
table(story, ["Setting", "Values", "Behaviour"], [
    ["NEXT_PUBLIC_API_MODE", "local (default) | rest", "local = current browser-local store + Next route proxies; rest = Spring Boot backend"],
    ["NEXT_PUBLIC_API_BASE_URL", "e.g. http://localhost:8080", "Only used in rest mode; token attached from the auth store"],
    ["Mock auth", "local mode", "AuthProvider auto-issues a demo session so existing screens keep working; login/register screens exercise the real flow"],
], [0.26, 0.24, 0.50], cap="Table 11-2: Integration switches")
sub(story, "11.3 Screen inventory and status")
table(story, ["Screen", "PRD ref", "Status"], [
    ["Dashboard (portfolio health, movement, warnings, alerts)", "18", "Done (local mode)"],
    ["Markets / watchlist", "18", "Done (local mode)"],
    ["Portfolio (holdings, allocation, P&L)", "18", "Done (local mode)"],
    ["Alerts (rules, history, create/edit)", "18", "Done (local mode)"],
    ["Scanner (templates, results, CSV export)", "12/extension", "Done (local mode)"],
    ["Research (news + instrument context)", "18", "Done (local mode)"],
    ["Settings (profile, risk, notification channels)", "18", "In progress (this release)"],
    ["Auth (login / register)", "7.1", "In progress (this release, mock session)"],
    ["AI Chat (streaming, citations)", "18", "V2 (needs backend agent)"],
    ["Stock detail page (fundamentals, AI analysis)", "18", "V2 (needs fundamentals data)"],
    ["IPO page (issue details, subscription, fit)", "18", "V2 (needs IPO provider)"],
], [0.44, 0.12, 0.44], cap="Table 11-3: Screen status")
bullets(story, [
    "State: the MarketProvider context remains the single store in local mode; in rest mode the same context hydrates from the REST API and mutates via API calls, so screens do not change.",
    "Design system: existing Tailwind tokens and ui.tsx primitives are the component library; new screens must compose them.",
    "Freshness: every price surface shows timestamp + source, in line with AC-13 (stale shown, never fabricated).",
])

# ════════ 12. NFRs ════════
section(story, "12. Non-Functional Requirements")
stat_row(story, [
    ("< 1 s", "Authenticated API target (excl. provider latency)"),
    ("99%", "Alert cycle completion despite provider faults"),
    ("100%", "AI tool calls audited"),
])
table(story, ["Area", "Requirement"], [
    ["Availability", "Dashboard and alert processing resilient to transient provider failures (cache fallback, STALE labelling)"],
    ["Performance", "Sub-second server processing for authenticated APIs excluding external provider latency; p95 endpoint budget tracked in CI"],
    ["Scalability", "Market data cached/shared by asset, never duplicated per user rule; provider calls batched"],
    ["Reliability", "Alert evaluation idempotent; exactly one notification per cooldown window (AC-05)"],
    ["Auditability", "Every AI tool call and material agent action traceable (AC-12)"],
    ["Observability", "Structured logs, metrics, traces, provider health checks, scheduler lag and queue depth"],
    ["Data freshness", "UI shows timestamp + source for live or cached data"],
    ["Extensibility", "Provider interfaces for market data, news, notifications and the LLM are replaceable"],
], [0.18, 0.82], cap="Table 12-1: NFR targets (PRD section 20)")

# ════════ 13. Environments & DevOps ════════
section(story, "13. Environments and DevOps")
table(story, ["Environment", "Purpose", "Composition"], [
    ["Local", "Development", "docker-compose: postgres, redis, api (Spring Boot), web (Next.js); seeded demo data"],
    ["Staging", "Integration + demo", "Single VM or PaaS (Render/Railway): managed Postgres, Redis, api, web; provider sandbox keys"],
    ["Production", "Personal deployment", "PaaS or small VPS; backups nightly; structured logs shipped off-box"],
], [0.15, 0.25, 0.60], cap="Table 13-1: Environments")
bullets(story, [
    "CI (GitHub Actions): frontend - lint, tsc, build; backend - Maven test, ArchUnit boundaries, Flyway checksum validation, Testcontainers integration tests (Postgres + Redis).",
    "Migrations run as a release step (Flyway validate + migrate); backward-compatible changes only while frontend deploys independently.",
    "Config via environment: DATABASE_URL, REDIS_URL, JWT_SECRET, LLM_API_KEY + model, provider keys; .env.example documented in the repo.",
])

# ════════ 14. Delivery Plan ════════
section(story, "14. Delivery Plan and Current Status")
table(story, ["Phase", "Deliverables", "Definition of done", "Status"], [
    ["Foundation (frontend)", "Next.js app, module structure, dashboard/markets/portfolio/alerts/research/scanner screens, design system", "All P0 screens render against local mode; build green", "Done"],
    ["Frontend readiness (this release)", "Typed API client + contracts, auth module (mock session), settings module, integration switches", "Screens compile against v1 contracts; mock/live switch in place", "In progress"],
    ["Foundation (backend)", "Spring Boot skeleton, Postgres + Flyway, auth + profile, docker-compose, CI", "User can register and persist core profile data (PRD 25)", "Next"],
    ["Portfolio + watchlist", "Holdings/watchlist APIs, metrics calculator, dashboard hydration", "Dashboard shows persisted holdings and computed metrics", "Planned"],
    ["Market layer", "Provider abstraction, Yahoo adapter, Redis cache, quote endpoints", "Stock data displays timestamped quotes with STALE fallback", "Planned"],
    ["Alert engine", "Rule model, scheduler, evaluator, history", "Tata Steel >= 200 use case works end-to-end without the browser open", "Planned"],
    ["Notifications", "In-app + email adapters, delivery history", "Triggered alert is delivered and recorded (AC-05)", "Planned"],
    ["AI layer", "Spring AI integration, tool registry, chat UI", "User can create an alert through natural language (AC-03)", "Planned"],
    ["Intelligence", "Stock/portfolio/news/IPO analysis services", "AI explains portfolio and researched assets with tool data", "Planned"],
    ["Autonomy (V3)", "Composite rules, thesis memory, digests, relevance engine", "Agent proactively surfaces relevant events with low noise", "Planned"],
], [0.19, 0.34, 0.33, 0.14], cap="Table 14-1: Phased delivery plan mapped from PRD section 25")

# ════════ 15. Risks ════════
section(story, "15. Risks and Mitigations")
table(story, ["Risk", "Impact", "Mitigation"], [
    ["Yahoo Finance is unofficial and can block or change without notice", "High",
     "Provider abstraction + Resilience4j fallback to last-good STALE data; Phase 2 moves live quotes to DhanHQ/SmartAPI licensed broker feeds"],
    ["LLM hallucination", "High", "Tool-first architecture, structured outputs, deterministic calculations, source context, guardrail system prompt"],
    ["Market data latency/inaccuracy", "High", "Timestamp + source on every observation, freshness labels, cache rules, provider health checks"],
    ["Notification overload", "Medium", "Relevance scoring, cooldowns, deduplication, user-configurable severity"],
    ["Vendor lock-in", "Medium", "Provider interfaces with normalized internal models; adapters are thin"],
    ["API rate limits / cost", "Medium", "Asset-level batching, 60 s cache, scheduled polling, provider-aware backoff, AI token budget"],
    ["Financial / regulatory exposure", "High", "Decision-support positioning, transparent uncertainty, explicit confirmations, legal review before broker/trade features"],
    ["Security breach", "High", "Least privilege, secure auth, secret management, audit logging, encrypted storage"],
    ["Single-maintainer scope creep", "Medium", "Modular monolith with enforced boundaries; phases gated by PRD acceptance criteria"],
], [0.30, 0.10, 0.60], cap="Table 15-1: Risk register")

# ════════ Appendices ════════
section(story, "Appendix A. Agent System Prompt (baseline)")
story.append(Paragraph(
    "You are a personal investment decision-support agent. Core rules: (1) Use tools for current market, "
    "IPO and portfolio data. (2) Never invent missing data. (3) Distinguish facts, calculations, "
    "interpretations and assumptions. (4) Consider the user profile and existing portfolio when relevant. "
    "(5) Explain risks and uncertainty. (6) Do not claim guaranteed returns, guaranteed allotment or "
    "certainty about future prices. (7) For material account or broker actions, require explicit "
    "confirmation. (8) Keep alert creation and rule evaluation deterministic in the backend. (9) When data "
    "is stale or unavailable, say so. (10) Prefer a useful, concise response with actionable next steps.",
    quote_st))
story.append(Spacer(1, 4))

section(story, "Appendix B. References")
bullets(story, [
    "Personal AI Investment Agent PRD v1.0 (September 2026) - source product document.",
    "Spring AI reference (tool calling, structured output): docs.spring.io/spring-ai.",
    "Market data: query1.finance.yahoo.com chart API (unofficial); eodhd.com; twelvedata.com; alphavantage.co.",
    "Broker feeds: dhan.co (DhanHQ API), smartapi.angelone.in, upstox.com developer docs, kite.trade.",
    "News: news.google.com/rss (in use), marketaux.com (entity-tagged), gnews.io.",
    "IPO data: apify.com/data_daemon/india-ipo-tracker (upcoming IPOs, GMP, subscription); chittorgarh.com live status.",
], style=bullet_tight)

doc.multiBuild(story, onFirstPage=header_footer, onLaterPages=header_footer)
print("body pages built:", doc.page)

# ━━ Cover (template 01 - HUD Data Terminal) ━━
from cover_render import render_cover, detect_fonts

cover_content = {
    "kicker": "TECHNICAL REQUIREMENTS DOCUMENT",
    "hero": "Meridian",
    "summary": ("Personal AI Investment Agent - production-grade blueprint covering the Next.js 16 frontend, "
                "Java 21 + Spring Boot backend, alert rule engine, Spring AI agent, the Indian market-data "
                "provider strategy, and the phased delivery plan."),
    "meta": "Version 1.0  |  Next.js 16  |  React 19  |  Java 21 + Spring Boot 3.5  |  PostgreSQL 16  |  Redis 7  |  Spring AI",
    "footer": "PERSONAL AI INVESTMENT AGENT  |  TRD-001  |  SEPTEMBER 2026",
    "year": "2026",
    "word": "TRD",
}
cover_palette = {"primary": "#334a55", "secondary": "#476b7e", "text": "#232627",
                 "muted": "#737a7d", "bg": "#ffffff"}
fonts = detect_fonts()
cover_pdf = os.path.join(HERE, "trd_cover.pdf")
render_cover("01", cover_content, cover_pdf, palette=cover_palette, fonts=fonts)

# ━━ Merge cover + body ━━
from pypdf import PdfReader, PdfWriter, Transformation

A4_W, A4_H = 595.28, 841.89


def normalize(page):
    w, h = float(page.mediabox.width), float(page.mediabox.height)
    if abs(w - A4_W) > 2 or abs(h - A4_H) > 2:
        page.add_transformation(Transformation().scale(sx=A4_W / w, sy=A4_H / h))
        page.mediabox.lower_left = (0, 0)
        page.mediabox.upper_right = (A4_W, A4_H)
    return page


writer = PdfWriter()
writer.add_page(normalize(PdfReader(cover_pdf).pages[0]))
for page in PdfReader(BODY_PDF).pages:
    writer.add_page(normalize(page))
writer.add_metadata({
    "/Title": "Meridian - Personal AI Investment Agent: Technical Requirements Document v1.0",
    "/Author": "Z.ai", "/Creator": "Z.ai",
    "/Subject": "TRD: production-grade architecture for the Meridian personal market intelligence platform",
})
final_pdf = os.path.join(OUT_DIR, "Meridian_TRD_v1.0.pdf")
with open(final_pdf, "wb") as f:
    writer.write(f)
print("FINAL:", final_pdf)
